version: "3"
services:
  web:
    image: tangerinejuice/webchat:back
    deploy:
      # replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:4000"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - webnet
    # deploy:
    #   replicas: 1
    #   placement:
    #     constraints: [node.role == manager]
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - webnet
networks:
  webnet:
